.\" Process this file with
.\" groff -man -Tascii tsh.1
.\"
.TH TSH 1 "OCTOBER 2012" "NU EECS 343" "NU EECS 343 - Operating Systems - Fall 2012"
.SH NAME
tsh \- A tiny shell
.SH SYNOPSIS
.B tsh
.SH DESCRIPTION
.B tsh
Supports the running of both built-in commands (e.g. cd, pwd, ...)  as well as external commands (e.g. ls). Also supports hitting Control + C to kill a process
.SH BUILT-IN COMMANDS
.IP exit
Quit tsh
.IP pwd
Prints the current working directory
.IP cd
Change the current working directory to PATH if PATH is included as an argument to cd, else change the current working directory to HOME
.SH DESIGN APPROACH
I followed the project skeleton/project handout specs as much as I could and filled out the skeleton methods.

I added the following helper functions as well:
(1) getCompleteFilePath takes an external command as its parameter and returns the full path of that command
and (2) existsAndExecutable checks a given file at a particular location to see if it exists and is executable

.SH AUTHOR
Jeanette Huang, jyh286, jeanettehuang2009@u.northwestern.edu
